---
title: "Merge actigraph and fitbit"
format: html
editor: visual
---

# Actigraph and fitbit data merging

```{r}
library(tidyverse, warn.conflicts = FALSE)
library(anytime)
```

## Read data

### Actigraph data

```{r raw data}
df_actigraph_raw <- read.csv("input/part2_daysummary_longformat.csv") |> 
  mutate(Date = anydate(calendar_date)) |> 
  # clean participant ID
  mutate(ID = str_extract(ID, "^[A-Z]{2}-\\d{1,3}-\\d{1,3}")) |> 
  rename(
    steps_actigraph = step_count_sum
  )
```

```{r day summary}
df_actigraph_daily <- df_actigraph_raw |>
  # get day summary observations
  filter(
    qwindow_name == "0-24hr"
  ) |>
  select(ID, Date, steps_actigraph) 
```

```{r actigraph hourly}

# Function to convert string to datetime object
convert_to_datetime <- function(datetime_str) {
  # Parse the date and hour separately
  date_part <- sub(" .*", "", datetime_str)
  hour_part <- as.numeric(sub(".* ", "", datetime_str))
  
  # Combine date and hour into a POSIXct object
  datetime <- ymd_h(paste(date_part, hour_part), tz = "UTC")
  
  return(datetime)
}

df_actigraph_hourly <- df_actigraph_raw |>
  # get hourly observations
  filter(
    N_hours_in_window == 1,
    N_valid_hours > 0 
  ) |>
  mutate(
    Time = sub(pattern = "-.*", replacement = "", x = qwindow_name),
    Datetime = convert_to_datetime(paste0(Date, Time))
  ) |> 
  select(ID, Datetime, steps_actigraph)
```

### Fitbit data

```{r daily data}
df_fitbit_daily <- read.csv("input/VALIDATION_daily_steps_hr.csv") |> 
  rename(
    ID = study.number,
    steps_fitbit = value.steps
  ) |> 
  mutate(
    Date = anydate(Date)
  )
```

```{r hourly data}
# this is currently not used
df_fitbit_hourly <- read.csv("input/VALIDATION_intraday_per_hour.csv") |> 
  rename(
  ID = study.number,
  steps_fitbit = value.steps
  ) |> 
  mutate(
    Datetime = anytime(Datetime)
  )
```

## Join fitbit and Actigraph data

### Daily data

```{r join daily data}
df_merged_daily <- left_join(
  df_actigraph_daily,
  df_fitbit_daily,
  by = c("Date", "ID")
  ) |> 
  select(
    ID, Date, steps_actigraph, steps_fitbit
  ) |> 
  arrange(ID, Date)

write.csv(df_merged_daily, "output/joined_daily.csv")
```

### Hourly data

```{r join hourly data}
df_merged_hourly <- left_join(
  df_actigraph_hourly,
  df_fitbit_hourly,
  by = c("Datetime", "ID")
  ) |> 
  select(
    ID, Datetime, steps_actigraph, steps_fitbit
  ) |> 
  arrange(ID, Datetime)

write.csv(df_merged_hourly, "output/joined_hourly.csv")
```
